### ISSUE TITLE
Parameter update of Experience Replay 

### ISSUE THREAD

**Issue by QiaoZhongzheng** [RaptorMai/online-continual-learning#9]
Hi. I have read your survey and am working on your codes. They are beautiful works.  I have a question about the parameter update of Experience Replay, which uses a batch of current input data (bacth_x) and a batch of memory samples (batch_mem).

Quote from the paper(ER part on Page 16): ''ER simply trains the model with the incoming and memory mini-batches together using the cross-entropy loss ''. My first view on this is to update the model's parameters with a combined batch (batch_x + bacth_mem), calculating the loss and backward propagate with only one step. In the codes, however, the update is realized by 2 backward steps, one calculated from the batch_x and one from the bacth_mem.  

I think the former way may be better, especially when using multiple mem_iters.  Is there any special consideration to update the model with batch_x and batch_mem separately? Which method did the original work of Experience Replay use?  

Look forward to your reply. Thanks.

**Comment by RaptorMai** [comment]
Hi, thank you so much for your interest in our work.

Firstly, please note that when you call .backward() without calling opt.step(), it accumulates the gradients into the .grad field. Therefore, when I do loss.backward() and then loss_mem.backward() without doing step(), it's the same as taking the grad of (loss+loss_mem). The only difference is that if we use architecture with batch norm layer, the loss will be different between loss(batch_x + bacth_mem) and loss(batch_x) +loss(batch_mem)  because of the batch norm. 

In terms of 
loss.backward() then  step() +  loss_mem.backward() then step()
Vs 
(loss+loss_mem).backward() then step(),

the later one works better empirically.  Hope I answer your question and please don't hesitate to let me.

**Comment by QiaoZhongzheng** [comment]
Thank you so much for your answer! I am new to torch and this answer made me clear very well. By the way, could you please tell me how to reproduce the OCI (Fig-1) results in the survey paper? Thanks.

**Comment by xiao910888** [comment]
> You can start with the following command. There are four config files that control the experiment.
> 
> * general config controls variables that are not changed during the experiment
> * data config controls variables related to the dataset
> * default method config controls variables for a specific method that are not changed during the experiment
> * method tuning config controls variables that are used for tuning during the experiment
> 
> python main_tune.py --general config/general_1.yml --data config/data/cifar100/cifar100_nc.yml --default config/agent/mir/mir_1k.yml --tune config/agent/mir/mir_tune.yml

Hello author, I ran your code, but I get an error

Setting up data stream
Files already downloaded and verified
Files already downloaded and verified
data setup time: 2.180302143096924
result/cifar100/nc
Task: 0, Labels:[26, 86, 2, 55, 75]
Task: 1, Labels:[93, 16, 73, 54, 95]
Task: 2, Labels:[53, 92, 78, 13, 7]
Task: 3, Labels:[30, 22, 24, 33, 8]
Task: 4, Labels:[43, 62, 3, 71, 45]
Task: 5, Labels:[48, 6, 99, 82, 76]
Task: 6, Labels:[60, 80, 90, 68, 51]
Task: 7, Labels:[27, 18, 56, 63, 74]
Task: 8, Labels:[1, 61, 42, 41, 4]
Task: 9, Labels:[15, 17, 40, 38, 5]
Task: 10, Labels:[91, 59, 0, 34, 28]
Task: 11, Labels:[50, 11, 35, 23, 52]
Task: 12, Labels:[10, 31, 66, 57, 79]
Task: 13, Labels:[85, 32, 84, 14, 89]
Task: 14, Labels:[19, 29, 49, 97, 98]
Task: 15, Labels:[69, 20, 94, 72, 77]
Task: 16, Labels:[25, 37, 81, 46, 39]
Task: 17, Labels:[65, 58, 12, 88, 70]
Task: 18, Labels:[87, 36, 21, 83, 9]
Task: 19, Labels:[96, 67, 64, 47, 44]
24
{'learning_rate': 0.0001, 'subsample': 25, 'weight_decay': 0.0001}
buffer has 1000 slots
Traceback (most recent call last):
  File "main_tune.py", line 57, in <module>
    main(args)
  File "main_tune.py", line 39, in main
    multiple_run_tune_separate(final_default_params, tune_params, args.save_path)
  File "E:\Project\online-continual-learning-main\experiment\run.py", line 218, in multiple_run_tune_separate
    single_tune(data_continuum, default_params, tune_params, params_keep, tmp_acc, run)
  File "E:\Project\online-continual-learning-main\experiment\run.py", line 252, in single_tune
    best_params = tune_hyper(tune_data, tune_test_loaders, default_params, tune_params, )
  File "E:\Project\online-continual-learning-main\experiment\tune_hyperparam.py", line 26, in tune_hyper
    agent = agents[final_params.agent](model, opt, final_params)
  File "E:\Project\online-continual-learning-main\agents\exp_replay.py", line 13, in __init__
    self.buffer = Buffer(model, params)
  File "E:\Project\online-continual-learning-main\utils\buffer\buffer.py", line 33, in __init__
    if self.params.buffer_tracker:
AttributeError: 'types.SimpleNamespace' object has no attribute 'buffer_tracker'

I just started learning this, thanks for your reply
